extend type Mutation {
  """
  ✨ Insert a single `Agent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  agent_insert(
    """
    Data object to insert into the table.
    """
    data: Agent_Data!
  ): Agent_KeyOutput! @fdc_generated(from: "Agent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DailyReward` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  dailyReward_insert(
    """
    Data object to insert into the table.
    """
    data: DailyReward_Data!
  ): DailyReward_KeyOutput! @fdc_generated(from: "DailyReward", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DeviceToken` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  deviceToken_insert(
    """
    Data object to insert into the table.
    """
    data: DeviceToken_Data!
  ): DeviceToken_KeyOutput! @fdc_generated(from: "DeviceToken", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Machine` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machine_insert(
    """
    Data object to insert into the table.
    """
    data: Machine_Data!
  ): Machine_KeyOutput! @fdc_generated(from: "Machine", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MachineLedger` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machineLedger_insert(
    """
    Data object to insert into the table.
    """
    data: MachineLedger_Data!
  ): MachineLedger_KeyOutput! @fdc_generated(from: "MachineLedger", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MachineSession` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machineSession_insert(
    """
    Data object to insert into the table.
    """
    data: MachineSession_Data!
  ): MachineSession_KeyOutput! @fdc_generated(from: "MachineSession", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Round` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  round_insert(
    """
    Data object to insert into the table.
    """
    data: Round_Data!
  ): Round_KeyOutput! @fdc_generated(from: "Round", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Wallet` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  wallet_insert(
    """
    Data object to insert into the table.
    """
    data: Wallet_Data!
  ): Wallet_KeyOutput! @fdc_generated(from: "Wallet", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WalletLedger` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  walletLedger_insert(
    """
    Data object to insert into the table.
    """
    data: WalletLedger_Data!
  ): WalletLedger_KeyOutput! @fdc_generated(from: "WalletLedger", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Agent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  agent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Agent_Data!]!
  ): [Agent_KeyOutput!]! @fdc_generated(from: "Agent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DailyReward` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  dailyReward_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DailyReward_Data!]!
  ): [DailyReward_KeyOutput!]! @fdc_generated(from: "DailyReward", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DeviceToken` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  deviceToken_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DeviceToken_Data!]!
  ): [DeviceToken_KeyOutput!]! @fdc_generated(from: "DeviceToken", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Machine` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machine_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Machine_Data!]!
  ): [Machine_KeyOutput!]! @fdc_generated(from: "Machine", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MachineLedger` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machineLedger_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MachineLedger_Data!]!
  ): [MachineLedger_KeyOutput!]! @fdc_generated(from: "MachineLedger", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MachineSession` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machineSession_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MachineSession_Data!]!
  ): [MachineSession_KeyOutput!]! @fdc_generated(from: "MachineSession", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Round` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  round_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Round_Data!]!
  ): [Round_KeyOutput!]! @fdc_generated(from: "Round", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Wallet` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  wallet_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Wallet_Data!]!
  ): [Wallet_KeyOutput!]! @fdc_generated(from: "Wallet", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WalletLedger` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  walletLedger_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WalletLedger_Data!]!
  ): [WalletLedger_KeyOutput!]! @fdc_generated(from: "WalletLedger", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Agent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Agent`.
  """
  agent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Agent_Data!
  ): Agent_KeyOutput! @fdc_generated(from: "Agent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DailyReward` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DailyReward`.
  """
  dailyReward_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DailyReward_Data!
  ): DailyReward_KeyOutput! @fdc_generated(from: "DailyReward", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DeviceToken` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DeviceToken`.
  """
  deviceToken_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DeviceToken_Data!
  ): DeviceToken_KeyOutput! @fdc_generated(from: "DeviceToken", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Machine` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Machine`.
  """
  machine_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Machine_Data!
  ): Machine_KeyOutput! @fdc_generated(from: "Machine", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MachineLedger` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MachineLedger`.
  """
  machineLedger_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MachineLedger_Data!
  ): MachineLedger_KeyOutput! @fdc_generated(from: "MachineLedger", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MachineSession` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MachineSession`.
  """
  machineSession_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MachineSession_Data!
  ): MachineSession_KeyOutput! @fdc_generated(from: "MachineSession", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Round` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Round`.
  """
  round_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Round_Data!
  ): Round_KeyOutput! @fdc_generated(from: "Round", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Wallet` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Wallet`.
  """
  wallet_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Wallet_Data!
  ): Wallet_KeyOutput! @fdc_generated(from: "Wallet", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WalletLedger` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WalletLedger`.
  """
  walletLedger_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WalletLedger_Data!
  ): WalletLedger_KeyOutput! @fdc_generated(from: "WalletLedger", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Agent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Agent`.
  """
  agent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Agent_Data!]!
  ): [Agent_KeyOutput!]! @fdc_generated(from: "Agent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DailyReward` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DailyReward`.
  """
  dailyReward_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DailyReward_Data!]!
  ): [DailyReward_KeyOutput!]! @fdc_generated(from: "DailyReward", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DeviceToken` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DeviceToken`.
  """
  deviceToken_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DeviceToken_Data!]!
  ): [DeviceToken_KeyOutput!]! @fdc_generated(from: "DeviceToken", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Machine` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Machine`.
  """
  machine_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Machine_Data!]!
  ): [Machine_KeyOutput!]! @fdc_generated(from: "Machine", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MachineLedger` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MachineLedger`.
  """
  machineLedger_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MachineLedger_Data!]!
  ): [MachineLedger_KeyOutput!]! @fdc_generated(from: "MachineLedger", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MachineSession` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MachineSession`.
  """
  machineSession_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MachineSession_Data!]!
  ): [MachineSession_KeyOutput!]! @fdc_generated(from: "MachineSession", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Round` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Round`.
  """
  round_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Round_Data!]!
  ): [Round_KeyOutput!]! @fdc_generated(from: "Round", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Wallet` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Wallet`.
  """
  wallet_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Wallet_Data!]!
  ): [Wallet_KeyOutput!]! @fdc_generated(from: "Wallet", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WalletLedger` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WalletLedger`.
  """
  walletLedger_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WalletLedger_Data!]!
  ): [WalletLedger_KeyOutput!]! @fdc_generated(from: "WalletLedger", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Agent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Agent` or `null` if not found.
  """
  agent_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Agent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Agent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Agent_Data!
  ): Agent_KeyOutput @fdc_generated(from: "Agent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DailyReward` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DailyReward` or `null` if not found.
  """
  dailyReward_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DailyReward_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyReward_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DailyReward_Data!
  ): DailyReward_KeyOutput @fdc_generated(from: "DailyReward", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DeviceToken` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DeviceToken` or `null` if not found.
  """
  deviceToken_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeviceToken_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeviceToken_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DeviceToken_Data!
  ): DeviceToken_KeyOutput @fdc_generated(from: "DeviceToken", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Machine` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Machine` or `null` if not found.
  """
  machine_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Machine_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Machine_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Machine_Data!
  ): Machine_KeyOutput @fdc_generated(from: "Machine", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MachineLedger` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MachineLedger` or `null` if not found.
  """
  machineLedger_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MachineLedger_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineLedger_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MachineLedger_Data!
  ): MachineLedger_KeyOutput @fdc_generated(from: "MachineLedger", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MachineSession` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MachineSession` or `null` if not found.
  """
  machineSession_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MachineSession_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineSession_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MachineSession_Data!
  ): MachineSession_KeyOutput @fdc_generated(from: "MachineSession", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Round` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Round` or `null` if not found.
  """
  round_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Round_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Round_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Round_Data!
  ): Round_KeyOutput @fdc_generated(from: "Round", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Wallet` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Wallet` or `null` if not found.
  """
  wallet_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Wallet_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Wallet_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Wallet_Data!
  ): Wallet_KeyOutput @fdc_generated(from: "Wallet", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WalletLedger` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WalletLedger` or `null` if not found.
  """
  walletLedger_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WalletLedger_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WalletLedger_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WalletLedger_Data!
  ): WalletLedger_KeyOutput @fdc_generated(from: "WalletLedger", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Agent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  agent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Agent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Agent_Data!
  ): Int! @fdc_generated(from: "Agent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DailyReward` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  dailyReward_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DailyReward_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DailyReward_Data!
  ): Int! @fdc_generated(from: "DailyReward", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DeviceToken` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  deviceToken_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DeviceToken_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DeviceToken_Data!
  ): Int! @fdc_generated(from: "DeviceToken", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Machine` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  machine_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Machine_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Machine_Data!
  ): Int! @fdc_generated(from: "Machine", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MachineLedger` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  machineLedger_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MachineLedger_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MachineLedger_Data!
  ): Int! @fdc_generated(from: "MachineLedger", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MachineSession` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  machineSession_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MachineSession_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MachineSession_Data!
  ): Int! @fdc_generated(from: "MachineSession", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Round` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  round_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Round_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Round_Data!
  ): Int! @fdc_generated(from: "Round", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Wallet` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  wallet_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Wallet_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Wallet_Data!
  ): Int! @fdc_generated(from: "Wallet", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WalletLedger` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  walletLedger_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WalletLedger_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WalletLedger_Data!
  ): Int! @fdc_generated(from: "WalletLedger", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Agent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  agent_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Agent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Agent_FirstRow
  ): Agent_KeyOutput @fdc_generated(from: "Agent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DailyReward` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  dailyReward_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DailyReward_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyReward_FirstRow
  ): DailyReward_KeyOutput @fdc_generated(from: "DailyReward", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DeviceToken` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  deviceToken_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeviceToken_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeviceToken_FirstRow
  ): DeviceToken_KeyOutput @fdc_generated(from: "DeviceToken", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Machine` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  machine_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Machine_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Machine_FirstRow
  ): Machine_KeyOutput @fdc_generated(from: "Machine", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MachineLedger` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  machineLedger_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MachineLedger_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineLedger_FirstRow
  ): MachineLedger_KeyOutput @fdc_generated(from: "MachineLedger", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MachineSession` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  machineSession_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MachineSession_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineSession_FirstRow
  ): MachineSession_KeyOutput @fdc_generated(from: "MachineSession", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Round` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  round_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Round_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Round_FirstRow
  ): Round_KeyOutput @fdc_generated(from: "Round", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Wallet` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  wallet_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Wallet_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Wallet_FirstRow
  ): Wallet_KeyOutput @fdc_generated(from: "Wallet", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WalletLedger` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  walletLedger_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WalletLedger_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WalletLedger_FirstRow
  ): WalletLedger_KeyOutput @fdc_generated(from: "WalletLedger", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Agent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  agent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Agent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Agent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DailyReward` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  dailyReward_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DailyReward_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DailyReward", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DeviceToken` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  deviceToken_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DeviceToken_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DeviceToken", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Machine` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  machine_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Machine_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Machine", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MachineLedger` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  machineLedger_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MachineLedger_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MachineLedger", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MachineSession` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  machineSession_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MachineSession_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MachineSession", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Round` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  round_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Round_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Round", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Wallet` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  wallet_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Wallet_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Wallet", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WalletLedger` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  walletLedger_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WalletLedger_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WalletLedger", purpose: DELETE_MULTIPLE)
}
