extend type Query {
  """
  ✨ Look up a single `Agent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  agent(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Agent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Agent_FirstRow
  ): Agent @fdc_generated(from: "Agent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DailyReward` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dailyReward(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DailyReward_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyReward_FirstRow
  ): DailyReward @fdc_generated(from: "DailyReward", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DeviceToken` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  deviceToken(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeviceToken_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeviceToken_FirstRow
  ): DeviceToken @fdc_generated(from: "DeviceToken", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Machine` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  machine(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Machine_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Machine_FirstRow
  ): Machine @fdc_generated(from: "Machine", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MachineLedger` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  machineLedger(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MachineLedger_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineLedger_FirstRow
  ): MachineLedger @fdc_generated(from: "MachineLedger", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MachineSession` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  machineSession(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MachineSession_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineSession_FirstRow
  ): MachineSession @fdc_generated(from: "MachineSession", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Round` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  round(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Round_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Round_FirstRow
  ): Round @fdc_generated(from: "Round", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Wallet` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  wallet(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Wallet_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Wallet_FirstRow
  ): Wallet @fdc_generated(from: "Wallet", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WalletLedger` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  walletLedger(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WalletLedger_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WalletLedger_FirstRow
  ): WalletLedger @fdc_generated(from: "WalletLedger", purpose: QUERY_SINGLE)
  """
  ✨ List `Agent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  agents(
    """
    Filter condition to narrow down the query results.
    """
    where: Agent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Agent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Agent_Having
  ): [Agent!]! @fdc_generated(from: "Agent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DailyReward` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dailyRewards(
    """
    Filter condition to narrow down the query results.
    """
    where: DailyReward_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DailyReward_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DailyReward_Having
  ): [DailyReward!]! @fdc_generated(from: "DailyReward", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DeviceToken` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  deviceTokens(
    """
    Filter condition to narrow down the query results.
    """
    where: DeviceToken_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DeviceToken_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DeviceToken_Having
  ): [DeviceToken!]! @fdc_generated(from: "DeviceToken", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Machine` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  machines(
    """
    Filter condition to narrow down the query results.
    """
    where: Machine_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Machine_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Machine_Having
  ): [Machine!]! @fdc_generated(from: "Machine", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MachineLedger` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  machineLedgers(
    """
    Filter condition to narrow down the query results.
    """
    where: MachineLedger_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MachineLedger_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MachineLedger_Having
  ): [MachineLedger!]! @fdc_generated(from: "MachineLedger", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MachineSession` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  machineSessions(
    """
    Filter condition to narrow down the query results.
    """
    where: MachineSession_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MachineSession_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MachineSession_Having
  ): [MachineSession!]! @fdc_generated(from: "MachineSession", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Round` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  rounds(
    """
    Filter condition to narrow down the query results.
    """
    where: Round_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Round_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Round_Having
  ): [Round!]! @fdc_generated(from: "Round", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Wallet` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  wallets(
    """
    Filter condition to narrow down the query results.
    """
    where: Wallet_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Wallet_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Wallet_Having
  ): [Wallet!]! @fdc_generated(from: "Wallet", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WalletLedger` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  walletLedgers(
    """
    Filter condition to narrow down the query results.
    """
    where: WalletLedger_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WalletLedger_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WalletLedger_Having
  ): [WalletLedger!]! @fdc_generated(from: "WalletLedger", purpose: QUERY_MULTIPLE)
}
